#!/bin/sh

# Utility script to run the Satin frontend on the specified arguments.

if [ -z "$SATIN_HOME" ];  then
    echo "please set SATIN_HOME to the location of your Satin installation" 1>&2
    exit 1
fi

exec "$SATIN_HOME"/scripts/satin-run -Xmx256M ibis.compile.Ibisc "$@"
